### ISSUE TITLE
Parsing issue >> TypeError: Cannot read properties of null (reading 'property')

### ISSUE THREAD

**Issue by impin2rex** [jup-ag/instruction-parser#21]
Issue Description:

I encountered a TypeError while using the instruction-parser library to parse a transaction. The error seems to occur during the decoding process.

Steps to Reproduce:

Run the command:
```
ts-node src/cli.ts lookup-tx --signature 2Bvxqo3S9ZyGmxjTyWS7pfRrVgSHKvPaj4H3z5Fir1CcjQhRRX8bQj2JCkxBVJWwCAfCBHBo1LyuvW2tzqXfYY6B --rpc https://api.mainnet-beta.solana.com
```
Expected Behavior:

The transaction should be parsed successfully without any errors.

Actual Behavior:

Encountered a TypeError during the transaction parsing process.
```
ts-node src/cli.ts lookup-tx --signature 2Bvxqo3S9ZyGmxjTyWS7pfRrVgSHKvPaj4H3z5Fir1CcjQhRRX8bQj2JCkxBVJWwCAfCBHBo1LyuvW2tzqXfYY6B --rpc https://api.mainnet-beta.solana.com
/Users/rex/Desktop/research/jupiter-instruction-parser/node_modules/buffer-layout/lib/Layout.js:1692
      dest[clo.property] = this.defaultLayout.decode(b, offset + contentOffset);
               ^
TypeError: Cannot read properties of null (reading 'property')
    at Union.decode (/Users/rex/Desktop/research/jupiter-instruction-parser/node_modules/buffer-layout/lib/Layout.js:1692:16)
    at Structure.decode (/Users/rex/Desktop/research/jupiter-instruction-parser/node_modules/buffer-layout/lib/Layout.js:1234:32)
    at Sequence.decode (/Users/rex/Desktop/research/jupiter-instruction-parser/node_modules/buffer-layout/lib/Layout.js:1090:34)
    at Structure.decode (/Users/rex/Desktop/research/jupiter-instruction-parser/node_modules/buffer-layout/lib/Layout.js:1234:32)
    at WrappedLayout.decode (/Users/rex/Desktop/research/jupiter-instruction-parser/node_modules/@coral-xyz/borsh/src/index.ts:111:37)
    at Structure.decode (/Users/rex/Desktop/research/jupiter-instruction-parser/node_modules/buffer-layout/lib/Layout.js:1234:32)
    at BorshInstructionCoder.decode (/Users/rex/Desktop/research/jupiter-instruction-parser/node_modules/@coral-xyz/anchor/src/coder/borsh/instruction.ts:107:28)
    at InstructionParser.getInitialAndFinalSwapPositions (/Users/rex/Desktop/research/jupiter-instruction-parser/src/lib/instruction-parser.ts:77:41)
    at /Users/rex/Desktop/research/jupiter-instruction-parser/src/index.ts:111:12
    at Generator.next (<anonymous>)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by siong1987** [comment]
resolved with this PR: https://github.com/jup-ag/instruction-parser/pull/24
