### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'toBase58')

### ISSUE THREAD

**Issue by amalashkevich** [jup-ag/instruction-parser#43]
There are signatures which cannot be parsed with the current instruction parser version.
Here is the list with a few of them:

- "3wsLbgu88DjHmfrFCyS5r5NJyyJaYjC9xUQYuSiJEUNBLxKyuEqR9b6WnbrScWaWVKBbCHdxb6TQuB16Ri3pqkzb"
- "5gwJLgdd6SeWk8UeTS1GXevGPveyH7E7oSzLwgUxRdSnm7u89vqnF8YyfrpLeqiBUSN9aChHsua15EQVouTBHk8A"
- "4qMM5JgARcSaBgdWqR3HWi5hh4f2kPoe5fHHiM19WQgiQFy9rYUtpsZrossG5xfyEAmYVAqLpqXH45EftYuPF2Rk"
- "5sXmsWi4JojDBX4A4qLVMU5WgCR4EuvkJdqZ7iLhPwwqPQrvssKjPjDqG16rQtsfo2xTNpG9am2TmwstAhDzDLT2"
- "5eMZiHbwzrC54p8VFRPH6xQxdtBQXg59a5w1cohX1hFmCcXBmSsJWSkRZK91QMvUQ5uz1qumyhGbH4XLEVDkLqW7"
- "4EGS5hAXKdGiyH4fBHrf59TjUMbFzgfjPfRWJWCevvdCjrUtjRxb1oBBCPj4S8pZ3vPFyCdw5nSNtk5Ru6pbc2WS"
- "wDLrUaRhNFtEw8d3BBMc4SSdU4fVj14DuLEsFSQg593Ci5ZSJJc4BZfgpJLBjZqf8GFKNgfnmD4BjangfFKJZge"
- "5b5WBCApQFANZMdTqbgM3GsHFocPoVmwVrPWbL7HXKcWBwWUR2txemsF76Nk7jxUcAY7CqCPUxJB9gfyv2qk99Yt"

Here is the stacktrace:

yarn start lookup-tx -r https://api.mainnet-beta.solana.com -s 3wsLbgu88DjHmfrFCyS5r5NJyyJaYjC9xUQYuSiJEUNBLxKyuEqR9b6WnbrScWaWVKBbCHdxb6TQuB16Ri3pqkzb
yarn run v1.22.19
$ ts-node src/cli.ts lookup-tx -r https://api.mainnet-beta.solana.com -s 3wsLbgu88DjHmfrFCyS5r5NJyyJaYjC9xUQYuSiJEUNBLxKyuEqR9b6WnbrScWaWVKBbCHdxb6TQuB16Ri3pqkzb
/Users/am/Documents/dev/jup-ag/instruction-parser/src/lib/event-parser.ts:280
    const inAccount = swap.inAccount.toBase58();
                                     ^
TypeError: Cannot read properties of undefined (reading 'toBase58')
    at EventParser.getInAndOutTransferInstructions (/Users/am/Documents/dev/jup-ag/instruction-parser/src/lib/event-parser.ts:280:38)
    at EventParser.<anonymous> (/Users/am/Documents/dev/jup-ag/instruction-parser/src/lib/event-parser.ts:50:41)
    at Generator.next (<anonymous>)
    at /Users/am/Documents/dev/jup-ag/instruction-parser/src/lib/event-parser.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/am/Documents/dev/jup-ag/instruction-parser/src/lib/event-parser.ts:4:12)
    at EventParser.getParsedEvents (/Users/am/Documents/dev/jup-ag/instruction-parser/src/lib/event-parser.ts:26:16)
    at /Users/am/Documents/dev/jup-ag/instruction-parser/src/index.ts:109:42
    at Generator.next (<anonymous>)
    at /Users/am/Documents/dev/jup-ag/instruction-parser/src/index.ts:8:71
error Command failed with exit code 1.

**Comment by serejke** [comment]
All transactions mentioned contain a Marinade Finance's `LiquidUnstake` instruction. Apparently the parser has issues recognizing this instruction.
